# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.formfill.enable", false);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.usedOnWindows10", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1468326077980");
user_pref("datareporting.policy.firstRunTime", "1468239677980");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1874);
user_pref("datareporting.sessions.current.main", 62);
user_pref("datareporting.sessions.current.startTime", "1468239677540");
user_pref("datareporting.sessions.current.totalTime", 10);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("ec.intl.accept_languages.done", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"de-DE@dictionaries.addons.mozilla.org\":{\"version\":\"2.0.4\",\"type\":\"dictionary\",\"descriptor\":\"C:\\\\PROGRA~2\\\\MOZILL~1\\\\browser\\\\extensions\\\\de-DE@dictionaries.addons.mozilla.org\",\"runInSafeMode\":false},\"en-gb@flyingtophat.co.uk\":{\"version\":\"1.19.6\",\"type\":\"dictionary\",\"descriptor\":\"C:\\\\PROGRA~2\\\\MOZILL~1\\\\browser\\\\extensions\\\\en-gb@flyingtophat.co.uk\",\"runInSafeMode\":false},\"fr-dicollecte@dictionaries.addons.mozilla.org\":{\"version\":\"5.3\",\"type\":\"dictionary\",\"descriptor\":\"C:\\\\PROGRA~2\\\\MOZILL~1\\\\browser\\\\extensions\\\\fr-dicollecte@dictionaries.addons.mozilla.org\",\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.2.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.2.0");
user_pref("extensions.lastPlatformVersion", "45.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"de-DE@dictionaries.addons.mozilla.org\":{\"d\":\"C:\\\\PROGRA~2\\\\MOZILL~1\\\\browser\\\\extensions\\\\de-DE@dictionaries.addons.mozilla.org\",\"e\":true,\"v\":\"2.0.4\",\"st\":1468026850524,\"mt\":1468026850516},\"en-gb@flyingtophat.co.uk\":{\"d\":\"C:\\\\PROGRA~2\\\\MOZILL~1\\\\browser\\\\extensions\\\\en-gb@flyingtophat.co.uk\",\"e\":true,\"v\":\"1.19.6\",\"st\":1468026850538,\"mt\":1468026850528},\"fr-dicollecte@dictionaries.addons.mozilla.org\":{\"d\":\"C:\\\\PROGRA~2\\\\MOZILL~1\\\\browser\\\\extensions\\\\fr-dicollecte@dictionaries.addons.mozilla.org\",\"e\":true,\"v\":\"5.3\",\"st\":1468026850575,\"mt\":1468026850542},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\PROGRA~2\\\\MOZILL~1\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.2.0\",\"st\":1464909503091}}}");
user_pref("gecko.buildID", "20160601155443");
user_pref("gecko.mstone", "45.2.0");
user_pref("intl.accept_languages", "en-gb,en,de,fr");
user_pref("intl.charsetmenu.browser.cache", "windows-1252");
user_pref("media.hardware-video-decoding.failed", true);
user_pref("network.proxy.autoconfig_url", "http://autoproxy.cec.eu.int/proxy.pac");
user_pref("network.proxy.type", 2);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("sanity-test.device-id", "0x95c0");
user_pref("sanity-test.driver-version", "8.56.1.16");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "45.2.0");
user_pref("toolkit.startup.last_success", 1468239677);
user_pref("toolkit.telemetry.previousBuildID", "20160601155443");
